spring:
  datasource:
    username: 유저네임입력[로컬]
    password: 비밀번호입력[로컬]
    url: jdbc:mysql://localhost:3306/[데이터베이스이름입력]?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
