

spring:
  profiles: live
  datasource:
    username: shopmaster
    password: springbook11
    url: jdbc:mysql://shop-book.ciclmc7wjq3o.ap-northeast-2.rds.amazonaws.com:3306/elct
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

